num = xlsread('C:\Users\Admin\OneDrive\FH Mechatronik\2.Semester\Embedded Systems 2\Systems Design\Project\Controller\Path.xlsx');
num = num';
num = num(1:230);
figure(1);
plot(linspace(0,size(num,2)*0.015,size(num,2)), num, "displayName", "real motor velocity");
hold on;
plot(simout.time, simout.data(:,1), "displayName", "target velocity");
hold on;
plot(simout.time, simout.data(:,2), "displayName", "simulated motor velocity");
legend;